name: Test with Gradle
on:
  push:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Test with Gradle
      run: gradle test
      env:
        AUTODIRECT_DB_HOST: ${{ secrets.AUTODIRECT_DB_HOST }}
        AUTODIRECT_DB_PASS: ${{ secrets.AUTODIRECT_DB_PASS }}
        AUTODIRECT_DB_PORT: ${{ secrets.AUTODIRECT_DB_PORT }}
        AUTODIRECT_DB_SSL: ${{ secrets.AUTODIRECT_DB_SSL }}
        AUTODIRECT_DB_USER: ${{ secrets.AUTODIRECT_DB_USER }}
        SENSO_API_KEY: ${{ secrets.SENSO_API_KEY }}
        SENSO_API_URL: ${{ secrets.SENSO_API_URL }}
